### ISSUE TITLE
The divider repeats itself on laptops and desktop devices

### ISSUE THREAD

**Issue by WDWaleed** [ManideepVaddepalli/Advice-Generator-App-Using-API#1]
The divider that is inserted after the quote repeats itself again and again depending on the size of the screen. Also the container does not look the same as in the design.

My opening this issue to edit the code and make the app look just the same as given in the design. If you want help, the kindly assign the issue to me and I'll start working on it.

**Comment by ManideepVaddepalli** [comment]
Thanks for the Feedback WDWaleed. I intentionally left it that way, I thought it was looking good even though the divider was repeating the direction-X.
